/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
(function(){var k={_attachScript:function(d,c){var e=new CKEDITOR.dom.element("script");e.setAttribute("src",d);e.on("error",c);CKEDITOR.document.getBody().append(e);return e},sendRequest:function(d,c,e,a){function b(){g&&(g.remove(),delete CKEDITOR._.jsonpCallbacks[h],g=null)}var f={};c=c||{};var h=CKEDITOR.tools.getNextNumber(),g;c.callback="CKEDITOR._.jsonpCallbacks["+h+"]";CKEDITOR._.jsonpCallbacks[h]=function(a){setTimeout(function(){b();e(a)})};g=this._attachScript(d.output(c),function(){b();
a&&a()});f.cancel=b;return f}};CKEDITOR.plugins.add("embedbase_qiniu",{lang:"cs,da,de,de-ch,en,eo,es,eu,fr,gl,id,it,ko,ku,nb,nl,pl,pt,pt-br,ru,sv,tr,ug,uk,zh,zh-cn",requires:"widget,notificationaggregator",onLoad:function(){CKEDITOR._.jsonpCallbacks={}},init:function(){CKEDITOR.dialog.add("embedBaseQiniu",this.path+"dialogs/embedbase.js")}});CKEDITOR.plugins.embedBaseQiniu={createWidgetBaseDefinition:function(d){var c,e=d.lang.embedbase_qiniu;return{mask:!0,template:"\x3cdiv\x3e\x3c/div\x3e",pathName:e.pathName,
_cache:{},urlRegExp:/^((https?:)?\/\/|www\.)/i,init:function(){this.on("sendRequest",function(a){this._sendRequest(a.data)},this,null,999);this.on("dialog",function(a){a.data.widget=this},this);this.on("handleResponse",function(a){if(!a.data.html){var b=this._responseToHtml(a.data.url,a.data.response);null!==b?a.data.html=b:(a.data.errorMessage="unsupportedUrl",a.cancel())}},this,null,999)},setVideoContent:function(a){this._setContent(a,'\x3cdiv style\x3d"left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"\x3e\x3cvideo style\x3d"position:absolute; width:100%;height:100%;" controls\x3d"" src\x3d"'+
a+'"\x3e\x3c/div\x3e')},setIframeContent:function(a){var b=$(a);b.css({width:"100%",height:"100%",position:"absolute",border:0,left:0,top:0});var f=$('\x3cdiv style\x3d"left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.2493%;"\x3e\x3c/div\x3e');f.append(b);this.setData("iframe",a);this.element.setHtml(f.prop("outerHTML"))},loadContent:function(a,b){function f(f){d.response=f;c.editor.widgets.instances[c.id]?c._handleResponse(d)&&(c._cacheResponse(a,f),b.callback&&b.callback()):
(CKEDITOR.warn("embedbase-widget-invalid"),d.task&&d.task.done())}b=b||{};var c=this,e=this._getCachedResponse(a),d={noNotifications:b.noNotifications,url:a,callback:f,errorCallback:function(a){c._handleError(d,a);b.errorCallback&&b.errorCallback(a)}};if(e)setTimeout(function(){f(e)});else return b.noNotifications||(d.task=this._createTask()),this.fire("sendRequest",d),d},isUrlValid:function(a){return this.urlRegExp.test(a)&&!1!==this.fire("validateUrl",a)},getErrorMessage:function(a,b,c){(c=d.lang.embedbase_qiniu[a+
(c||"")])||(c=a);return(new CKEDITOR.template(c)).output({url:b||""})},_sendRequest:function(a){var b=this,c=k.sendRequest(this.providerUrl,{url:encodeURIComponent(a.url)},a.callback,function(){a.errorCallback("fetchingFailed")});a.cancel=function(){c.cancel();b.fire("requestCanceled",a)}},_handleResponse:function(a){var b={url:a.url,html:"",response:a.response};if(!1!==this.fire("handleResponse",b))return a.task&&a.task.done(),this._setContent(a.url,b.html),!0;a.errorCallback(b.errorMessage);return!1},
_handleError:function(a,b){a.task&&(a.task.cancel(),a.noNotifications||d.showNotification(this.getErrorMessage(b,a.url),"warning"))},_responseToHtml:function(a,b){return"photo"==b.type?'\x3cimg src\x3d"'+CKEDITOR.tools.htmlEncodeAttr(b.url)+'" alt\x3d"'+CKEDITOR.tools.htmlEncodeAttr(b.title||"")+'" style\x3d"max-width:100%;height:auto" /\x3e':"video"==b.type||"rich"==b.type?(b.html=b.html.replace(/<iframe/g,'\x3ciframe tabindex\x3d"-1"'),b.html):null},_setContent:function(a,b){this.setData("url",
a);this.element.setHtml(b)},_createTask:function(){if(!c||c.isFinished())c=new CKEDITOR.plugins.notificationAggregator(d,e.fetchingMany,e.fetchingOne),c.on("finished",function(){c.notification.hide()});return c.createTask()},_cacheResponse:function(a,b){this._cache[a]=b},_getCachedResponse:function(a){return this._cache[a]}}},_jsonp:k}})();